[package]
name = "mod-fix-multiplayer-locks"
edition = "2021"
version.workspace = true

[lib]
crate-type = ["cdylib"]
name="fix_multiplayer_locks"

[dependencies]
log = { workspace = true }
p3-api = { path = "../p3-api" }
hooklet = { workspace = true }
