[workspace]

members = [
    "aimcli",
    "cprcli",
    "p3-agent",
    "p3-agent-loader",
    "p3-aim",
    "p3-aim-sys",
    "p3-api",
    "p3-api-dotnet",
    "p3-influxdb",
]
exclude = [
]
