[package]
name = "p3-aim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3-aim-sys = { path = "../p3-aim-sys" }
log = "0.4"

[dev-dependencies]
simple_logger = "4.1"
