[package]
name = "p3-rou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"
byteorder = "1.5.0"
log = "0.4"
simple_logger = "4.1"
