// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace P3Api
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "p3_api";

        /// <summary>Open Patrician3.exe for Reading.</summary>
        [DllImport(__DllName, EntryPoint = "new_api", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern DotnetOpenProcessP3AccessApi* new_api(uint pid);

        [DllImport(__DllName, EntryPoint = "read_town", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TownData* read_town(DotnetOpenProcessP3AccessApi* api, TownId raw_town_id);

        [DllImport(__DllName, EntryPoint = "get_ware_scaling", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int get_ware_scaling(WareId ware_id);

        [DllImport(__DllName, EntryPoint = "free_town", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_town(TownData* town);

        [DllImport(__DllName, EntryPoint = "dummy_office_data", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void dummy_office_data(OfficeData* _town);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TownData
    {
        public StorageData storage;
        public fixed int get_daily_consumptions_citizens[24];
        public ByteBuffer offices;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct OfficeData
    {
        public ushort merchant_id;
        public StorageData storage;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct StorageData
    {
        public fixed int wares[24];
        public fixed int daily_consumption_businesses[24];
        public fixed int daily_production[24];
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct DotnetOpenProcessP3AccessApi
    {
    }


    public enum WareId : ushort
    {
        Grain = 0,
        Meat = 1,
        Fish = 2,
        Beer = 3,
        Salt = 4,
        Honey = 5,
        Spices = 6,
        Wine = 7,
        Cloth = 8,
        Skins = 9,
        WhaleOil = 10,
        Timber = 11,
        IronGoods = 12,
        Leather = 13,
        Wool = 14,
        Pitch = 15,
        PigIron = 16,
        Hemp = 17,
        Pottery = 18,
        Bricks = 19,
        Sword = 20,
        Bow = 21,
        Crossbow = 22,
        Carbine = 23,
    }

    public enum TownId : ushort
    {
        Edinburgh = 0,
        Newcastle = 1,
        Scarborough = 2,
        Boston = 3,
        London = 4,
        Bruges = 5,
        Haarlem = 6,
        Harlingen = 7,
        Groningen = 8,
        Cologne = 9,
        Bremen = 10,
        Ripen = 11,
        Hamburg = 12,
        Flensburg = 13,
        Luebeck = 14,
        Rostock = 15,
        Bergen = 16,
        Stavanger = 17,
        Toensberg = 18,
        Oslo = 19,
        Aalborg = 20,
        Goeteborg = 21,
        Naestved = 22,
        Malmoe = 23,
        Ahus = 24,
        Stockholm = 25,
        Visby = 26,
        Helsinki = 27,
        Stettin = 28,
        Ruegenwald = 29,
        Gdansk = 30,
        Torun = 31,
        Koenigsberg = 32,
        Memel = 33,
        Windau = 34,
        Riga = 35,
        Pernau = 36,
        Reval = 37,
        Ladoga = 38,
        Novgorod = 39,
    }


}
    