[build]
rustflags = [
#    "-C", "link-arg=-nostdlib",
#    "-C", "link-arg=-static",
#    "-C", "link-arg=-Wl,-T./patch.ld,--build-id=none",
#    "-C", "relocation-model=pic",
    "-C", "link-arg=/ENTRY:_start",
    "-C", "link-arg=/SUBSYSTEM:WINDOWS",
]
