[package]
name = "p3-api-dotnet"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
p3-api = { path = "../p3-api" }
log = "0.4"
csbindgen = "1.7.0"

[build-dependencies]
csbindgen = "1.7.0"
